spring.application.name=backend

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/restaurant_erp
spring.datasource.username=root
spring.datasource.password=2007@25thangam

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true