spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: false

  mail:
    host: localhost
    port: 25

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    access-token-expiration-ms: 3600000
    refresh-token-expiration-ms: 8640000
  security:
    max-failed-login-attempts: 5
    account-lock-duration-minutes: 30
